// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Calendar: typeof import('./components/shared/Calendar.vue')['default']
    EditTime: typeof import('./components/shared/EditTime.vue')['default']
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElCard: typeof import('element-plus/lib')['ElCard']
    ElCol: typeof import('element-plus/lib')['ElCol']
    ElMain: typeof import('element-plus/lib')['ElMain']
    ElPopover: typeof import('element-plus/lib')['ElPopover']
    ElRow: typeof import('element-plus/lib')['ElRow']
    ElScrollbar: typeof import('element-plus/lib')['ElScrollbar']
    ElTimePicker: typeof import('element-plus/lib')['ElTimePicker']
    ICarbonArrowLeft: typeof import('~icons/carbon/arrow-left')['default']
    ICarbonArrowRight: typeof import('~icons/carbon/arrow-right')['default']
    ICarbonEdit: typeof import('~icons/carbon/edit')['default']
    Loading: typeof import('element-plus/lib')['ElLoadingDirective']
    WorkTimeStatistics: typeof import('./components/WorkTimeStatistics.vue')['default']
  }
}

export { }
