// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElHeader: typeof import('element-plus/lib')['ElHeader']
    ElMenu: typeof import('element-plus/lib')['ElMenu']
    ElMenuItem: typeof import('element-plus/lib')['ElMenuItem']
    NavMenu: typeof import('./components/NavMenu.vue')['default']
  }
}

export { }
